# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\TranslatorQT.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import gather
from os import system
from codecs import encode

wordlist_address_linux = '/mnt/c/Users/Hessam/Desktop/WordLists.txt' # wsl format
wordlist_address_windows = r'C:\\Users\\Hessam\\Desktop\\WordLists.txt' # windows format
# wordlist_address_windows = 'notepad.exe ' + r'C:\\Users\\Hessam\\Desktop\\WordLists.txt' # windows format

# ReLoad All Existing words in file to prevent ReTranslate
existing_words = []
try:
    with open(wordlist_address_windows, 'r+') as file:
        lines = file.readlines()
        for line in lines:
            if not line.startswith('|'):
                existing_words.append(line[:-3].strip())
    file.close()
except:
    print('No File Already Exists, Creating...')
    open(wordlist_address_windows, 'w+').close()



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(454, 748)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(130, 590, 211, 51))
        self.search_button.setObjectName("search_button")
        self.terminal_output = QtWidgets.QTextBrowser(self.centralwidget)
        self.terminal_output.setGeometry(QtCore.QRect(10, 10, 431, 471))
        self.terminal_output.setObjectName("terminal_output")
        self.user_input = QtWidgets.QLineEdit(self.centralwidget)
        self.user_input.setGeometry(QtCore.QRect(70, 508, 311, 71))
        self.user_input.setObjectName("user_input")
        self.log = QtWidgets.QTextBrowser(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(10, 650, 431, 41))
        self.log.setObjectName("log")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 454, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        self.search_button.clicked.connect(self.search_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def search_clicked(self):
        current_word = self.user_input.text()
        current_meanings = gather.Translate(current_word)

        # self.terminal_output.setText(current_meanings)
        if current_meanings:
            with open(wordlist_address_windows, 'a+', encoding='utf-8') as file:
                # Store In a FILE & Show in the Box
                self.terminal_output.setText(current_word.capitalize() + ' :' + '\n') # Show WORD
                file.writelines(current_word.capitalize() + ' :' + '\n') # Write WORD

                for this_mean in current_meanings: # Write & Show MEANINGS
                    my_string = '||\t' + this_mean + '\n'
                    self.terminal_output.append(my_string.strip())
                    file.writelines(my_string)
                    # file.writelines('|| \t' + this_mean + '\n')


                self.terminal_output.append('|-----------------------------------------------------------\n\n')
                file.writelines('|-----------------------------------------------------------\n\n')

                existing_words.append(current_word.strip().capitalize()) # Add to Existing List to avoid duplication
                file.flush()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_button.setText(_translate("MainWindow", "Translate!"))


if __name__ == "__main__":
    print('start')
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

